language: rust
rust:
  - nightly
script:
- cargo build --verbose --all
- cargo test --verbose --all --all-features 
- rustup component add rustfmt
- cargo fmt --all -- --check
- rustup component add clippy
- cargo clippy --all --all-features